package pcd.ass01.common;

/**
 * A logical game operation generated by a producer thread.
 *
 * <p>Commands decouple input production from model mutation: the EDT and the
 * bot create command objects, while the game loop later executes them on the
 * model in a serialized point of the frame.
 */
public interface GameCommand {

    /** Executes this command on the provided model. */
    void execute(GameModel model);
}
