pekko {
  actor {
    provider = cluster
    serialization-bindings {
      "pcd.ass04.alarm.JsonSerializable" = jackson-json
    }
  }

  remote.artery.canonical.hostname = "127.0.0.1"
  remote.artery.canonical.port = 25520

  cluster {
    seed-nodes = [
      "pekko://alarm-cluster@127.0.0.1:25520",
      "pekko://alarm-cluster@127.0.0.1:25521",
      "pekko://alarm-cluster@127.0.0.1:25522"
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    split-brain-resolver.active-strategy = keep-majority
  }
}
